### ISSUE TITLE
br

### ISSUE THREAD

**Issue by Chris00** [mirage/ocaml-cow#100]
Should `br` just have the type `val br : t`?

**Comment by Chris00** [comment]
The same question can also be raised for the other `void_elements`.

**Comment by Chris00** [comment]
For the rare cases one would like to add attributes to these elements, one could provide `with_attrs : ?cls:string -> ?id:string -> ?attrs:(string * string) list -> t -> t` (attributes added to all elements of the list).

**Comment by samoht** [comment]
Sounds like a good idea

**Comment by Chris00** [comment]
I have not implemented with `with_attrs` because when attributes make sense, they are better put as optional arguments to the function.
