### ISSUE TITLE
HTML output should be Polyglot

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-cow#13]
Cow currently violates the Polyglot <http://www.w3.org/TR/html-polyglot/> spec in a number of ways. Most importantly:

- [x] No doctype
- [ ] No xmlns
- [x] Unnecessary inclusion of XML declaration
- [ ] No case normalization
- [x] Collapses elements without EMPTY content model
- [ ] Other minor DOM additions
- [ ] No `<script>` handling

**Comment by samoht** [comment]
This is not in scope for this project, see [markup.ml](https://github.com/aantron/markup.ml)
