### ISSUE TITLE
Using characters “ ” produces a faulty output.

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-cow#27]
To reproduce, just try to use “ or ” in a page.

**Comment by Chris00** [comment]
This seems to work fine:
```ocaml
# let x = Cow.Html.of_string "<p>“Hi”</p>";;
val x : Cow.Html.t =
  [`El ((("", "p"), []), [`Data "\226\128\156Hi\226\128\157"])]
# Cow.Html.to_string x;;
- : string = "<p>\226\128\156Hi\226\128\157</p>"
```

**Comment by samoht** [comment]
Can't reproduce.

**Comment by chrismamo1** [comment]
I've had this problem before:

    <:html<<div id="$str:x$">...</div>&>>

it appears that the problem is solved by doing

    <:html<<div id=$str:x$>...</div>&>>

instead, since the syntax extension detects that you're trying to use an anti quote for a property value and automatically adds quotes, I believe.
