### ISSUE TITLE
xml/html parsing and embedded markdown (mirage-decks)

### ISSUE THREAD

**Issue by mor1** [mirage/ocaml-cow#40]
see the email thread; basically, inline markdown as used by mirage-decks doesn't work with cow because there's no way to pass through invalid uses of xml significant characters (& < > etc). from the thread:
mort
> it works for some of the markdown, but there are some things it doesn't help. basically, it stops cow barfing if there are characters like & < > when it parses the input; but cow then escapes these which means the js in the page that parses the markdown can't recognise them.

> eg., `<&>` in a markdown fragment either causes cow to barf (parse error), or if surrounded by CDATA cow turns it into `&lt;&amp;&gt;` in the html returned to the browser, so the js then renders it as the corresponding string literal (in html, "&amp;lt;&amp;amp;&amp;gt;") in a monospaced font. 

> the best i can think of is some way to explicitly tell cow to not parse a chunk of input and leave it "raw". or else i'll have to revert to serving fragments out of files and not use cow at all.

anil
> I can't think of anything else immediately that might help, short of an HTML parser (which is more permissive about such things than an XML parser).  Could you create an issue on https://github.com/mirage/ocaml-cow/issues about this so we don't forget?

...reverting to serving files for now.

**Comment by samoht** [comment]
No more syntax extensions, no more bugs.
