### ISSUE TITLE
Incompatible with core

### ISSUE THREAD

**Issue by rgrinberg** [mirage/ocaml-cow#41]
The Json module uses the `List.mem_assoc` function which core provides under `List.Assoc.mem`. 

I'm not sure what's the correct way to handle this problem. For now I'm just wrapping cow code generation with `open Caml` and re-opening `Core.Std` but I'm sure I will run into more issues if I start using more type_conv extensions.

For example: see the sample at: https://github.com/rgrinberg/opium#example

**Comment by Chris00** [comment]
One way to work around this bug would be to add some aliases for the modules you need at the very top of your file.  For example `module CowAliasList_ = List`.

**Comment by samoht** [comment]
No more `List.mem_assoc`
