### ISSUE TITLE
Compatibility with the new ezjsonm

### ISSUE THREAD

**Issue by rgrinberg** [mirage/ocaml-cow#54]
cc @samoht

**Comment by toby-m** [comment]
Looks like the "with json" extensions are broken with the new ezjson. I've had a go at fixing it but it's a bit beyond my experience. This is what I've found so far:

https://github.com/mirage/ocaml-cow/blob/master/syntax/json/extension.ml#L195
This value of "error" here is `Json.value` not `Json.t` which `Json.to_string` now takes. Substituting a dummy string in works, but I'm not sure how to give a good error there.

https://github.com/mirage/ocaml-cow/blob/master/lib/json.ml#L92
Runtime_exception can be made `of string * value` here (and the mli).

Also, nested records like this:
```
type date = { day : int; month : int; year : int } with json
type event = { title : string; date : date } with json
```
Generate functions like this:
```    
let rec json_of_event event : Json.t =
  `O [ ("title", (`String event.title)); ("date", (json_of_date event.date)) ]
```

But the output of json_of_date is Json.t and it wants a Json.value. Changing it to this works but I can't figure out the <<:expr>> stuff to make that happen.
``` 
  `O [ ("title", (`String event.title)); ("date", Json.value (json_of_date event.date)) ]
```

**Comment by samoht** [comment]
Thanks for the report, I'm looking into that now.
