### ISSUE TITLE
Html.link should be Html.a

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-cow#63]
`link` is a different tag in HTML from `a`. As this value was just added by @Chris00, it shouldn't cause any breakage.

The `link` type and value `html_of_link` should also be renamed, eventually. These renamings will cause breakage in at least opam2web.

**Comment by Chris00** [comment]
`html_of_link`: renamed into what?  The type `link` should then also be renamed.  May you explain the point of the type `link` BTW?  I would expect `href` to be a `Uri.t` and then, if one wants to carry the couple `(text, href)` around, why not to do it with just a… couple??

**Comment by dsheets** [comment]
I think the purpose of `link` was to have a type to talk about HTML anchor values without making an ad hoc type or referring to serialization. I can't seem to trace the origin of those signature elements (starts at import commit which is first in repo) but it seems @avsm's idea at the time was to develop the module into a library of constructors and OCaml types to represent common HTML structures. Most likely `Uri.t` was not available when this code was originally written.

I don't really have an opinion on whether it should stay or go but it *is* deceptively named now that we have `img` and `link` constructors.

**Comment by Chris00** [comment]
OK — I only deprecated them instead of providing alternatives.

**Comment by Chris00** [comment]
>  @avsm's idea at the time was to develop the module into a library of constructors and OCaml types to represent common HTML structures.

Right but if a separate [HTML library](https://github.com/mirage/ocaml-cow/issues/62#issuecomment-71708024) is provided, these functions rather belong to it.

**Comment by dsheets** [comment]
In #62, I propose that *sloppy parsing* of HTML should live in another library. I absolutely still believe that *high-quality generation* of HTML belongs in `cow`.

**Comment by dsheets** [comment]
Thanks for the patch! Could you mark the `link` type and `html_of_link` deprecated in the documentation comments, too?

**Comment by Chris00** [comment]
> In #62, I propose that sloppy parsing of HTML should live in another library. I absolutely still believe that *high-quality generation* of HTML belongs in cow.

To make sure I understand: you mean generating HTML that enforces some rules like having a unique `id` attribute, not having `<head>` inside `<body>`, ..., not solely that all blocks are well closed.

**Comment by dsheets** [comment]
To some extent, those rules may belong here but my feeling is that many of the more global properties should not be enforced directly. Perhaps we could offer validation functions?

Properties that are most amenable to library aid seem to be those that can be ensured via simple construction (elaborate types are probably not appropriate here, judging by the current lack of them).
