### ISSUE TITLE
Parse_error expanding anti-quotation within quotes

### ISSUE THREAD

**Issue by kayceesrk** [mirage/ocaml-cow#69]
Here is the failing test case:

    utop #  let mk_html foo = <:html< <id name="#$str:foo$"> "Hello, world!" </id> >>;;
    val mk_html : bytes -> Cow.Xml.t = <fun> 
    utop # mk_html "test";;
    Exception: Parsing.Parse_error.

The problem is with anti-quotation within quotes. The desired behavior can be achieved with:

    utop #  let mk_html foo = <:html< <id name=$str:"#"^foo$> "Hello, world!" </id> >>;;

It would help if the error message was more precise.

**Comment by samoht** [comment]
No more syntax extension, no more bug.

**Comment by kayceesrk** [comment]
:+1:
