### ISSUE TITLE
Cannot use labeled argument assignment in html quotations

### ISSUE THREAD

**Issue by tbrk** [mirage/ocaml-cow#86]
This code fails
```ocaml
let tcol_in_row ?(classes="col-xs-12 col-md-6") cols =
  let inrow x = <:html< <div class=$str:classes$>$x$</div> >> in
  <:html< <div class="row">$list:List.map inrow cols$</div> >>

let narrow_in_row cols =
  <:html< $tcol_in_row ~classes:"col-xs-1" cols$ >>
```
with the message
```
[ERROR] tcol_in_row ~classes is not a valid tag.
Allowed tags are [opt|int|flo|str|uri|list|alist|attrs] or the empty one.File "htmlutil.ml", line 9, characters 9-26:
While expanding quotation "html" in a position of "expr":
  Camlp4: Uncaught exception: Parsing.Parse_error
```

I'm sorry that I can't submit a patch; I am completely new to Camlp4.

BTW, I think that ocaml-cow (and the libraries it relies on) is great. I just finished using it to generate our new team website (http://parkas.di.ens.fr/). The generator (~1300 LoOC) slurps up a bunch of markdown and csv files and spits out html.

**Comment by dsheets** [comment]
Hi @tbrk, I think you can work around this by doing something like

```ocaml
let narrow_in_row cols =
  let classes = "col-xs-1" in
  <:html< $tcol_in_row ~classes cols$ >>
```

The issue is with the use of the colon (`:`) which is interpreted as the end of a quotation class. We can fix the parser to not choke on this but in the meantime, there is a solution.

**Comment by avsm** [comment]
On 11 Feb 2016, at 08:02, Timothy Bourke <notifications@github.com> wrote:
> 
> [ERROR] tcol_in_row ~classes is not a valid tag

Yeah, unfortunately the ~ causes problems in the parser, so avoiding labelled arguments is a workaround for now.

**Comment by tbrk** [comment]
Thanks for the workarounds. I just wanted to report this issue because it seemed natural to me to use labelled arguments in those contexts and I was surprised when it wouldn't compile.
